In [1]:
#1 Creating Matrices

In [65]:
#1.a.i
# CJR = [3,10,18] , YOE = [25,15,5] 
import numpy as np
a = np.array ([[3,10,18],
               [25,15,5]])
# 1.a.ii 
# 2023-4-0422 = [2,0,2] & [4,2,2]
b = np.array ([[2,0,2],
               [4,2,2]])

In [19]:
# 1.b 
print ("Matrix_A:\n",a)
print ("Matrix_B:\n",b)

Matrix_A:
 [[ 3 10 18]
 [25 15  5]]
Matrix_B:
 [[2 0 2]
 [4 2 2]]


In [21]:
# 2 Matrix Addition 

In [59]:
# 2.a 
c = (a+b)
# 2.b 
print ("Matrix_C:\n",c)

Matrix_C:
 [[ 5 10 20]
 [29 17  7]]


In [25]:
# 3 Scalar Multiplication 

In [45]:
# 3.a 
d = a*2
# 3.b 
print ("Matrix_D:\n",d)

Matrix_D:
 [[ 6 20 36]
 [50 30 10]]


In [29]:
# 4 Matrix Transpose 

In [49]:
# 4.a
transposed_b = b.T
# 4.b
print ("Matrix_E:\n",transposed_b)

Matrix_E:
 [[2 4]
 [0 2]
 [2 2]]


In [33]:
# 5 Matrix Multiplication 

In [57]:
# 5.a 
f = np.dot(c,transposed_b)
# 5.b
print ("Matrix_F:\n",f)

Matrix_F:
 [[ 50  80]
 [ 72 164]]


In [37]:
# 6 Sum of all Elements 

In [63]:
# 6.a 
C = np.sum (c) 
# 6.b 
print ("Sum_Matrix_C:\n",C)

Sum_Matrix_C:
 88


In [41]:
# 7 Zero Matrix 

In [61]:
# 7.a 
G = np.zeros((2,3))
# 7.b 
print ("Matrix_G:\n",h)

Matrix_G:
 [[0. 0. 0.]
 [0. 0. 0.]]
